<?php

declare(strict_types=1);

namespace Priebera\ContextReporter\Export;

use Priebera\ContextReporter\Domain\ReportSource;

/**
 * Human readable Markdown version of a report, suitable for pasting into an
 * issue tracker.
 *
 * All report values are literal text: Markdown characters are escaped, so
 * titles, descriptions and labels cannot create images, links, HTML,
 * mentions or block structure. URLs inside text are shown as code; values
 * that consist of a URL only become explicit autolinks, whose text is the
 * target itself.
 *
 * @internal
 */
final readonly class MarkdownReportExporter
{
    private const URL = '~(?:[a-z][a-z0-9+.\-]*://|www\.)[^\s<>()\[\]`"\'|]+~i';
    private const ESCAPED_CHARACTERS = '/([\\\\`*_\[\]|~#]|@(?=\w))/';

    public function __construct(
        private ContextDetailsFormatter $detailsFormatter,
    ) {}

    /**
     * @param array<string, mixed> $payload
     */
    public function export(array $payload): string
    {
        $markers = (new ReportMarkers($this->detailsFormatter))->fromPayload($payload);
        $lines = [];
        $lines[] = '# ' . $this->inline($markers['report.title']);
        $lines[] = '';
        $lines[] = '| Field | Value |';
        $lines[] = '|---|---|';
        $overview = [
            'Report ID' => $markers['report.id'],
            'Created' => $markers['report.createdAt'],
            'Source' => ReportSource::tryFrom((string)($payload['source'] ?? ''))?->getLabel() ?? '',
            'Reporter' => $markers['reporter.name'],
            'Project' => trim($markers['project.name'] . ($markers['project.environment'] !== '' ? ' (' . $markers['project.environment'] . ')' : '')),
            'Report link' => $markers['report.url'],
        ];
        foreach ($overview as $label => $value) {
            if ($value !== '') {
                $lines[] = '| ' . $label . ' | ' . $this->cell($value) . ' |';
            }
        }

        $lines[] = '';
        $lines[] = '## Description';
        $lines[] = '';
        $description = trim($markers['report.description']);
        if ($description === '') {
            $lines[] = '_No description given._';
        } else {
            foreach (explode("\n", $description) as $line) {
                $lines[] = rtrim('> ' . $this->paragraph($line));
            }
        }

        $lines[] = '';
        $lines[] = '## Context';
        $lines[] = '';
        $lines[] = $this->paragraph($markers['context.summary']);
        foreach ($this->detailsFormatter->buildSections($payload) as $section) {
            $lines[] = '';
            $lines[] = '### ' . $this->inline($section['title']);
            $lines[] = '';
            $lines[] = '| Field | Value |';
            $lines[] = '|---|---|';
            foreach ($section['rows'] as $label => $value) {
                $lines[] = '| ' . $this->cell($label) . ' | ' . $this->cell($value) . ' |';
            }
        }

        $lines[] = '';
        $lines[] = '## Attachments';
        $lines[] = '';
        $attachments = is_array($payload['attachments'] ?? null) ? $payload['attachments'] : [];
        if ($attachments === []) {
            $lines[] = '_None._';
        }
        foreach ($attachments as $attachment) {
            if (!is_array($attachment)) {
                continue;
            }
            $lines[] = sprintf(
                '- %s (%s, %d×%d px, %s, SHA-256 %s)',
                $this->inline((string)($attachment['filename'] ?? '')),
                $this->inline((string)($attachment['mediaType'] ?? '')),
                (int)($attachment['width'] ?? 0),
                (int)($attachment['height'] ?? 0),
                self::formatBytes((int)($attachment['size'] ?? 0)),
                $this->inline((string)($attachment['sha256'] ?? '')),
            );
        }

        $generator = is_array($payload['generator'] ?? null) ? $payload['generator'] : [];
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '_Generated by ' . $this->inline(trim((string)($generator['name'] ?? '') . ' ' . (string)($generator['version'] ?? ''))) . '._';

        return implode("\n", $lines) . "\n";
    }

    public static function formatBytes(int $bytes): string
    {
        if ($bytes < 1024) {
            return $bytes . ' B';
        }
        if ($bytes < 1024 * 1024) {
            return rtrim(rtrim(number_format($bytes / 1024, 1, '.', ''), '0'), '.') . ' KB';
        }
        return rtrim(rtrim(number_format($bytes / 1024 / 1024, 1, '.', ''), '0'), '.') . ' MB';
    }

    /**
     * Literal text within a line.
     */
    private function inline(string $text): string
    {
        $result = '';
        $offset = 0;
        preg_match_all(self::URL, $text, $matches, PREG_OFFSET_CAPTURE);
        foreach ($matches[0] as [$url, $position]) {
            $result .= $this->escape(substr($text, $offset, $position - $offset)) . '`' . $url . '`';
            $offset = $position + strlen($url);
        }
        return $result . $this->escape(substr($text, $offset));
    }

    /**
     * Literal text at the start of a line: list markers, headings and
     * thematic breaks are escaped as well.
     */
    private function paragraph(string $text): string
    {
        return (string)preg_replace(
            ['/^(\s*)([+\-=])/', '/^(\s*\d+)([.)])/'],
            ['$1\\\\$2', '$1\\\\$2'],
            $this->inline($text),
        );
    }

    private function cell(string $text): string
    {
        $text = trim((string)preg_replace('/\s*\R\s*/', ' ', $text));
        if (preg_match('~^https?://[^\s<>`|]+$~iD', $text) && filter_var($text, FILTER_VALIDATE_URL) !== false) {
            return '<' . $text . '>';
        }
        return $this->inline($text);
    }

    private function escape(string $text): string
    {
        $text = (string)preg_replace('/&(?=#?[a-z0-9]+;)/i', '&amp;', $text);
        $text = str_replace(['<', '>'], ['&lt;', '&gt;'], $text);
        return (string)preg_replace(self::ESCAPED_CHARACTERS, '\\\\$1', $text);
    }
}
